/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Controller.Controller;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.Delayed;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.text.View;

/**
 *
 * @author cleitin
 */
public class TelaInicial extends javax.swing.JFrame {

    private final Controller controller;
    public String laranja,banana;
   
  

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        controller = new Controller(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1Texto = new javax.swing.JTextField();
        jTextField2Key = new javax.swing.JTextField();
        jLabelResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1Texto.setBackground(new java.awt.Color(46, 46, 46));
        jTextField1Texto.setForeground(new java.awt.Color(125, 125, 125));
        jTextField1Texto.setText("Texto ");
        getContentPane().add(jTextField1Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 115, 360, -1));

        jTextField2Key.setBackground(new java.awt.Color(46, 46, 46));
        jTextField2Key.setForeground(new java.awt.Color(125, 125, 125));
        jTextField2Key.setText("Chave ");
        jTextField2Key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2KeyActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2Key, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 188, 347, -1));

        jLabelResult.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelResult.setForeground(new java.awt.Color(255, 255, 255));
        jLabelResult.setText("resultado");
        getContentPane().add(jLabelResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 387, -1, -1));

        jLabel1.setForeground(new java.awt.Color(65, 65, 65));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fundo preto.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 530, 30));

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DECIFRAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CIFRAR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xarope.png"))); // NOI18N
        jLabel2.setText("ALEGRIA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 440));

        jButton2.setText("DECIFRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 120, 110));

        jButton1.setText("CIFRAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    
    private void jTextField2KeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2KeyActionPerformed
      
        
    }//GEN-LAST:event_jTextField2KeyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    
        int[] k = controller.StringtoAscii(getjTextField1Texto().getText());
        int[] p = controller.StringtoAscii(getjTextField2Key().getText());
        String j = controller.AsciitoBin(k);
        String x = controller.AsciitoBin(p);
        
        if (k.length == p.length){
           
        String w = controller.XOROp(j, x);
        
       String g = controller.toAscii(w);
       laranja = g;
        
        
        banana = x;
        
        String b = controller.bintoAscii(g);
        
        
            
            
        }else{
            getjLabelResult().setText("COLOQUE A CHAVE E O TEXTO COM O MESMO TAMANHO");
        }
       
        
        
      
       
       
        
       
        
               
       
      
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String abacate = (controller.toAscii(controller.XOROp(laranja, banana)));
       
        String carambola = controller.bintoAscii(abacate);
        
        controller.asciitochar(carambola);
        
        
        
        //System.out.println(controller.XOROp(x, controller.abacaxi));
        // controller.toAscii( controller.XOROp(x, controller.abacaxi));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
           
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JTextField getjTextField1Texto() {
        return jTextField1Texto;
    }

    public void setjTextField1Texto(JTextField jTextField1Texto) {
        this.jTextField1Texto = jTextField1Texto;
    }

    public JTextField getjTextField2Key() {
        return jTextField2Key;
    }

    public void setjTextField2Key(JTextField jTextField2Key) {
        this.jTextField2Key = jTextField2Key;
    }

    public JLabel getjLabelResult() {
        return jLabelResult;
    }

    public void setjLabelResult(JLabel jLabelResult) {
        this.jLabelResult = jLabelResult;
    }

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JTextField jTextField1Texto;
    private javax.swing.JTextField jTextField2Key;
    // End of variables declaration//GEN-END:variables

    public void setjLabelResult(String key) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
